spring:
  application:
    name: wallet-transaction-system

  datasource:
    url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: wallet-consumers
    producer:
      properties:
        linger.ms: 0
        acks: all

app:
  kafka:
    topic:
      transaction: wallet-transactions

server:
  port: ${PORT:8080}
