spring:
  datasource:
    url: jdbc:mysql://localhost:3306/walletdb?useSSL=false&serverTimezone=UTC
    username: wallet_user
    password: change-me
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: wallet-consumers
    producer:
      properties:
        linger.ms: 0
        acks: all

app:
  kafka:
    topic:
      transaction: wallet-transactions

